config/routes.rb
Rails.application.routes.draw do
 
  resources :groups do
    resources :crews
    resources :concierts
  end
  root 'groups#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :group

  def get_group_name
    self.group.name
  end
  
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: %w[ show edit update destroy ]

  # GET /crews
  # GET /crews.json
  def index
    @group = Group.find params[:group_id]
    @crews = @group.crews
  end

  # GET /crews/1
  # GET /crews/1.json
  def show
    @group = Group.find params[:group_id]
    @crew = Crew.find(params[:id])
  end

  # GET /crews/new
  def new
    @group = Group.find params[:group_id]
    @crew = Crew.new
  end

  # GET /crews/1/edit
  def edit
    @group = Group.find params[:group_id]
    @crew = Crew.find(params[:id])
  end

  # POST /crews
  # POST /crews.json
  def create
    @group = Group.find params[:group_id]
    @crew = Crew.new(crew_params)
    @crew.group = @group
    respond_to do |format|
      if @crew.save
        format.html { redirect_to group_crew_path(@group,@crew), notice: "Crew was successfully created." }
        format.json { render :show, status: :created, location: @crew }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crews/1
  # PATCH/PUT /crews/1.json
  def update
    @group = Group.find params[:group_id]
    @crew = Crew.find(params[:id])
    respond_to do |format|
      if @crew.update(crew_params.merge(group: @group))
        format.html { redirect_to group_crew_path(@group, @crew) , notice: "Crew was successfully updated." }
        format.json { render :show, status: :ok, location: @crew }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crews/1
  # DELETE /crews/1.json
  def destroy
    @crew = Crew.find(params[:id])
    @crew.destroy
    respond_to do |format|
      format.html { redirect_to group_crews_url, notice: "Crew was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crew_params
      params.require(:crew).permit(:name, :group_id)
    end
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/views/crews/_form.html.erb
<%= form_with(model: [@group,crew], local: true) do |form| %>
  <% if crew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
        <% crew.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crews/edit.html.erb
<h1>Editing Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Show', group_crew_path(@group,@crew) %> |
<%= link_to 'Back', group_crews_path(@group) %>

app/views/crews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crews.each do |crew| %>
      <tr>
        <td><%= crew.name %></td>
        <td><%= link_to 'Show', group_crew_path(@group,crew)  %></td>
        <td><%= link_to 'Edit', edit_group_crew_path(@group,crew) %></td>
        <td><%= link_to 'Destroy', group_crew_path(@group, crew), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', group_path(@group) %>
<%= link_to 'New Crew', new_group_crew_path(@group) %>

app/views/crews/new.html.erb
<h1>New Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Back', group_crews_path %>

app/views/crews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crew.name %>
</p>


<%= link_to 'Edit', edit_group_crew_path(@group,@crew) %> |
<%= link_to 'Back', group_crews_path(@group) %>