config/routes.rb
Rails.application.routes.draw do
 
  resources :groups do
    resources :crews
    resources :concierts
  end
  root 'groups#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
    validates :name, :type_group, presence: true
    enum type_group: [:men, :women, :band]
    has_many :concierts, dependent: :destroy
    has_many :crews, dependent: :destroy

    
    #methods instance
    #quantity crew
    def cant_crew
        Crew.references(:groups).where(group_id: id).count
    end
    #first date
    def date_debut
        no = "No ha debutado"
       debut =Conciert.references(:groups).where(group_id: id).order(date: :asc).first
       if debut.nil?
        no
       else
        debut.date
       end

    end
    #quantity concierts
    def cant_concierts
        Conciert.references(:groups).where(group_id: id).count
    end
    #quantity people
    def cant_people
        people =Conciert.references(:groups).where(group_id: id).pluck :people
        people.sum
    end

    def cant_concierts_month
        time= Time.now.strftime("%Y-%m-01")
        t =Time.now.strftime("%Y-%m-%d")
        Conciert.references(:groups).where(group_id: id).where(date: time..t).count
    end
    def last_conciert
        no = "No tiene concierto"
        last=Conciert.references(:groups).where(group_id: id).order(date: :desc).first
        if last.nil?
            no
        else
            last.date.strftime("%Y-%B-%A")
        end
    end

    def max_people
        no = "0"
        max = Conciert.references(:groups).where(group_id: id).pluck :people
        if max.blank?
            no
        else
            max.max
        end
    end
    def max_duration
        no = "0"
        duration = Conciert.references(:groups).where(group_id: id).pluck :duration
        
        if duration.blank?
            no
        else
            duration.max.strftime("%Hh:%Mm")
        end
    end
    def get_crews
        no = "0"
        crew= Crew.references(:groups).where(group_id: id).pluck :name
        
        if crew.blank?
            no
        else
            crew.join(", ")
        end
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %w[ show edit update destroy ]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :type_group)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type_group %>
     <%= form.select :type_group, Group.type_groups.keys %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Type</th>
      <th scope="col">Crews</th>
      <th scope="col">Debut</th>
      <th scope="col">Concierts</th>
      <th scope="col">People</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.type_group %></td>
        <td><%= group.cant_crew%></td>
        <td><%= group.date_debut %></td>
        <td><%= group.cant_concierts %></td>
        <td><%= group.cant_people %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered table-hover">
  <tbody>
    <tr>
      <th><strong>Name:</strong></th>
      <td> <%= @group.name %></td>
    </tr>
    <tr>
      <th><strong>Type:</strong></th>
      <td><%= @group.type_group %></td>
    </tr>
    <tr>
      <th><strong>Concerts in the month:</strong></th>
      <td><%= @group.cant_concierts_month %></td>
    </tr>
    <tr>
      <th><strong>Last Conciert:</strong></th>
      <td><%= @group.last_conciert%></td>
    </tr>
    <tr>
      <th><strong>Max People:</strong></th>
      <td><%= @group.max_people %></td>
    </tr>
     <tr>
      <th><strong>Max Duration:</strong></th>
      <td><%= @group.max_duration %></td>
    </tr>
      <tr>
      <th><strong>Crews</strong></th>
      <td><%= @group.get_crews%></td>
    </tr>
  </tbody>
</table>
<a href="<%=  group_concierts_path(@group) %>" class="btn btn-success text-white">View All Concierts</a>
<a href="<%= group_crews_path(@group) %>" class="btn btn-warning text-white">View All Crews</a>
<a href="<%= groups_path %>" class="btn btn-primary text-white">Back</a>