config/routes.rb
Rails.application.routes.draw do
 
  resources :groups do
    resources :crews
    resources :concierts
  end
  root 'groups#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/conciert.rb
class Conciert < ApplicationRecord
  belongs_to :group

  def get_group_name
    self.group.name
  end
  
end

app/controllers/concierts_controller.rb
class ConciertsController < ApplicationController
  before_action :set_conciert, only: %w[ show edit update destroy ]

  # GET /concierts
  # GET /concierts.json
  def index
    @group = Group.find params[:group_id]
   
    @concierts = @group.concierts
  end

  # GET /concierts/1
  # GET /concierts/1.json
  def show
    @group = Group.find params[:group_id]
    @conciert = Conciert.find(params[:id])
  end

  # GET /concierts/new
  def new
    @group = Group.find params[:group_id]
    @conciert = Conciert.new
    
  end

  # GET /concierts/1/edit
  def edit
    @group = Group.find params[:group_id]
    @conciert = Conciert.find(params[:id])
  end

  # POST /concierts
  # POST /concierts.json
  def create
    @group = Group.find params[:group_id]
    @conciert = Conciert.new(conciert_params)
    @conciert.group = @group
    respond_to do |format|
      if @conciert.save
        format.html { redirect_to group_conciert_path(@group,@conciert), notice: "Conciert was successfully created." }
        format.json { render :show, status: :created, location: @conciert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conciert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concierts/1
  # PATCH/PUT /concierts/1.json
  def update
    @group = Group.find params[:group_id]
    @conciert = Conciert.find(params[:id])
    respond_to do |format|
      if @conciert.update(conciert_params.merge(group: @group))
        format.html { redirect_to group_conciert_path(@group,@conciert), notice: "Conciert was successfully updated." }
        format.json { render :show, status: :ok, location: @conciert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conciert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concierts/1
  # DELETE /concierts/1.json
  def destroy
    @conciert = Conciert.find(params[:id])
    @conciert.destroy
    respond_to do |format|
      format.html { redirect_to group_concierts_url, notice: "Conciert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conciert
      @conciert = Conciert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conciert_params
      params.require(:conciert).permit(:people, :duration, :date, :group_id)
    end
end

app/helpers/concierts_helper.rb
module ConciertsHelper
end

app/views/concierts/_form.html.erb
<%= form_with(model: [@group,conciert], local: true) do |form| %>
  <% if conciert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conciert.errors.count, "error") %> prohibited this conciert from being saved:</h2>

      <ul>
        <% conciert.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :people %>
    <%= form.number_field :people %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.time_select :duration %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concierts/edit.html.erb
<h1>Editing Conciert</h1>

<%= render 'form', conciert: @conciert %>

<%= link_to 'Show', group_conciert_path(@group,@conciert) %> |
<%= link_to 'Back', group_concierts_path(@group) %>

app/views/concierts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concierts</h1>

<table>
  <thead>
    <tr>
      <th>People</th>
      <th>Duration</th>
      <th>Date</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concierts.each do |conciert| %>
      <tr>
        <td><%= conciert.people %></td>
        <td><%= conciert.duration.strftime("%Hh:%Mm") %></td>
        <td><%= conciert.date %></td>
        <td><%= conciert.get_group_name %></td>
        <td><%= link_to 'Show', group_conciert_path(@group, conciert) %></td>
        <td><%= link_to 'Edit', edit_group_conciert_path(@group, conciert) %></td>
        <td><%= link_to 'Destroy', group_conciert_path(@group, conciert), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', group_path(@group) %>
<%= link_to 'New Conciert', new_group_conciert_path(@group) %>

app/views/concierts/new.html.erb
<h1>New Conciert</h1>

<%= render 'form', conciert: @conciert %>

<%= link_to 'Back', group_concierts_path %>

app/views/concierts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>People:</strong>
  <%= @conciert.people %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @conciert.duration %>
</p>

<p>
  <strong>Date:</strong>
  <%= @conciert.date %>
</p>

<p>
  <strong>Group:</strong>
  <%= @conciert.group_id %>
</p>

<%= link_to 'Edit', edit_group_conciert_path(@group,@conciert) %> |
<%= link_to 'Back',group_concierts_path(@group)%>